# Generated by Django 3.2.6 on 2022-01-15 16:27

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='user/default_user.png', upload_to=accounts.models.user_directory_path_profile)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
