# Generated by Django 3.2.6 on 2022-01-15 18:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/user/default_user.png', upload_to=accounts.models.user_directory_path_profile),
        ),
    ]
