# Generated by Django 3.2.6 on 2022-01-15 19:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220115_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user/default_user.jpg', upload_to=accounts.models.user_directory_path_profile),
        ),
    ]
